// Code generated by "stringer -type=CaseSensitivity"; DO NOT EDIT.

package tspath

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CaseSensitive-0]
	_ = x[CaseInsensitive-1]
}

const _CaseSensitivity_name = "CaseSensitiveCaseInsensitive"

var _CaseSensitivity_index = [...]uint8{0, 13, 28}

func (i CaseSensitivity) String() string {
	if i >= CaseSensitivity(len(_CaseSensitivity_index)-1) {
		return "CaseSensitivity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CaseSensitivity_name[_CaseSensitivity_index[i]:_CaseSensitivity_index[i+1]]
}
